-- create caculator field for index
SET ANSI_NULLS, ANSI_PADDING,
	ANSI_WARNINGS, ARITHABORT,
	CONCAT_NULL_YIELDS_NULL,
	QUOTED_IDENTIFIER ON
SET NUMERIC_ROUNDABORT OFF
GO

-- create nonclustered index
CREATE NONCLUSTERED INDEX 平均單價_索引
ON 估價單 (平均單價 ASC)
INCLUDE (產品編號);

-- create view table
SET ANSI_NULLS, ANSI_PADDING,
	ANSI_WARNINGS, ARITHABORT,
	CONCAT_NULL_YIELDS_NULL,
	QUOTED_IDENTIFIER ON
SET NUMERIC_ROUNDABORT OFF
GO
CREATE VIEW dbo.
--WITH ENCRYPTION, SCHEMABINDING, VIEW_METADATA
AS
	SELECT * 
	FROM dbo.table_name
	--WITH CHECK OPTION
GO
