CREATE TABLE StorageFile(
	id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	uploadFileLocation NVARCHAR(1024) NOT NULL,
)

CREATE TABLE StorageFile2(
	id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	uploadFileLocation NVARCHAR(1024) NOT NULL,
	
)